version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    container_name: "nginx_container"
    networks:
      - django-network
    ports:
      - "80:80"
    depends_on:
      - django-app
    restart: always
  django-app:
    build:
      context: .
    image: django_app
    container_name: "django_cont"
    env_file:
      - .env
    networks:
      - django-network
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:latest
    container_name: "db_cont"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - django-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 30s 
      timeout: 10s
      retries: 5
    restart: always
