apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-dep
  namespace: app
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labeles:
        app: notes-app
    spec:
      containers:
        -name: notes-app-c
         image: afroz25/notes-app:latest
          ports:
          - containerPort: 80
